---
toc: false
---

# Grafieken per reservaat

```{r}
#| label: setup
#| include: FALSE

knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      fig.width = 10)

library(dplyr)  
library(knitr)
library(kableExtra)
library(tidyr)
library(ggplot2)
library(INBOtheme)
theme_set(theme_inbo(base_size = 12, transparent = FALSE))
library(plotly)
library(stringr)

```

```{r}

#data inlezen en definieren
carbon_by_plot <- read.csv2('../../data/carbon_by_plot.csv', header = TRUE, dec=',', sep=';')
dendro_by_diam_plot <- read.csv2('../../data/dendro_by_diam_plot.csv', header = TRUE, dec=',', sep=';')
dendro_by_diam_plot_species <- read.csv2('../../data/dendro_by_diam_plot_species.csv', header = TRUE, dec=',', sep=';')
dendro_by_plot <- read.csv2('../../data/dendro_by_plot.csv', header = TRUE, dec=',', sep=';')
logs_by_decay_plot <- read.csv2('../../data/logs_by_decay_plot.csv', header = TRUE, dec=',', sep=';')
logs_by_decay_plot_species <- read.csv2('../../data/logs_by_decay_plot_species.csv', header = TRUE, dec=',', sep=';')
regeneration_by_plot <- read.csv2('../../data/regeneration_by_plot.csv', header = TRUE, dec=',', sep=';')
regeneration_by_plot_height <- read.csv2('../../data/regeneration_by_plot_height.csv', header = TRUE, dec=',', sep=';')
regeneration_by_plot_height_species <- read.csv2('../../data/regeneration_by_plot_height_species.csv', header = TRUE, dec=',', sep=';')
plotinfo <- read.csv2('../../data/plotinfo.csv', header = TRUE, dec=',', sep=';')
all_names2 <- read.csv2('../../data/all_names2.csv', header = TRUE, dec=',', sep=';')
metadata <- read.csv2('../../data/metadata.csv', header = TRUE, dec=',', sep=';')

dendro_by_diam_plot_species <- left_join(dendro_by_diam_plot_species, all_names2, by= "name_sc")

logs_by_decay_plot_species <- left_join(logs_by_decay_plot_species, all_names2, by= "name_sc")
regeneration_by_plot_height_species <- left_join(regeneration_by_plot_height_species, all_names2, by= "name_sc")

dendro_by_diam_plot_species$period <- as.factor(dendro_by_diam_plot_species$period)
logs_by_decay_plot$period <- as.factor(logs_by_decay_plot$period)
logs_by_decay_plot_species$period <- as.factor(logs_by_decay_plot_species$period)
plotinfo$period <- as.factor(plotinfo$period)
regeneration_by_plot_height_species$period <- as.factor(regeneration_by_plot_height_species$period)
dendro_by_plot$period <- as.factor(dendro_by_plot$period)
carbon_by_plot$period <- as.factor(carbon_by_plot$period)

dendro_by_diam_plot_species$dbh_class_5cm <- str_remove(dendro_by_diam_plot_species$dbh_class_5cm, " cm") %>%
    str_replace(" - ", "-")
#unique(dendro_by_diam_plot_species$dbh_class_5cm)
dendro_by_diam_plot_species$dbh_class_5cm <- factor(dendro_by_diam_plot_species$dbh_class_5cm, 
  levels = c("5-10", "10-15", "15-20", "20-25", "25-30", "30-35", "35-40", "40-45", "45-50", "50-55", "55-60", "60-65", "65-70", "70-75", "75-80", "80-85", "85-90", 
"90-95", "95-100", "100-105","105-110", "110-115", "115-120", "120-125", "125-130", "130-135", "135-140", "140-145", "145-150", "150-155", "155-160"))
# Problem: dit kan wellicht eleganter onafhankelijk van welke levels precent zijn

regeneration_by_plot_height_species$height_class <- str_remove(regeneration_by_plot_height_species$height_class, " cm") %>%
  str_replace(" - ", "-")
#unique(regeneration_by_plot_height_species$height_class)
regeneration_by_plot_height_species$height_class <- ifelse(is.na(regeneration_by_plot_height_species$height_class),"U", regeneration_by_plot_height_species$height_class)

regeneration_by_plot_height_species$height_class <- ifelse(regeneration_by_plot_height_species$height_class %in% c("0-30", "30-50"), "0-50",regeneration_by_plot_height_species$height_class)

regeneration_by_plot_height_species$height_class <- factor(regeneration_by_plot_height_species$height_class, levels = c("0-50", "50-130", "50-200", "> 130", "> 200", "U"))

regeneration_by_plot_height_species <- regeneration_by_plot_height_species[regeneration_by_plot_height_species$mean_number_of_regeneration_ha>0,]

```

<!-- AUTOGENERATED-START -->

> Autogenerated content below Do not edit manually.

<!-- AUTOGENERATED-END -->
