---
title: Meetnet Spontane Dynamiek Bosreservaten
toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE)

library(tidyverse)
library(plotly)
library(crosstalk)
```

## Resultaten

::: panel-tabset
## Biomassa

```{r}
setwd("C:/Users/els_lommelen/Documents/gitrepos/forest-reserves/data")
stat_carbon <- read.csv2('carbon_by_plot.csv', header = TRUE, dec=',', sep=';')
stat_dendro <- read.csv2('dendro_by_plot.csv', header = TRUE, dec=',', sep=';')
plotinfo <- read.csv2('plotinfo.csv', header = TRUE, dec=',', sep=';')

plotinfo$forest_reserve <- as.factor(plotinfo$forest_reserve)

stat_carbon_wide <- left_join(stat_carbon, plotinfo, by=c("plot_id","period")) %>%
   select(forest_reserve, period, BiomassAboveGr_t_ha, BiomassBelowGr_t_ha,
           BiomassTotalLiving_t_ha, CarbonAboveGr_t_ha, CarbonBelowGr_t_ha,
           CarbonTotalLiving_t_ha ) %>%
  pivot_longer(cols = c("BiomassAboveGr_t_ha", "BiomassBelowGr_t_ha",
           "BiomassTotalLiving_t_ha", "CarbonAboveGr_t_ha", "CarbonBelowGr_t_ha",
           "CarbonTotalLiving_t_ha"),
           names_to = "label", values_to = "value") %>%
  group_by(forest_reserve, period, label) %>%
  summarise(mean= mean(value), uci_diff= qnorm(1-0.05/2)*sd(value)/sqrt(n()))  %>%
  pivot_wider(names_from = "label", values_from = c("mean", "uci_diff")) %>%
  mutate(offset_period = (period - 2.5) * 0.2)

 stat_carbon_wide$forest_reserve <- fct_reorder(stat_carbon_wide$forest_reserve, stat_carbon_wide$mean_BiomassAboveGr_t_ha)

```

```{r}
sd <- SharedData$new(stat_carbon_wide)

bscols(widths = c(4, 4),
       filter_select("forest_reserve", "Select forest reserve", sd, ~forest_reserve),
       filter_checkbox("period", "Select period", sd, ~period))

# volgende code is qua logica gebaseerd op https://stackoverflow.com/questions/50921790/split-points-by-a-factor-in-a-plotly-scatter-plot met
# forest_reserve = cluster
# period = group
# y_location heb ik op basis van offset_period berekend in de plot-functie zelf omdat het anders misloopt met de sortering van de reservaten

# het draait, maar nog op te lossen is:

# - bij het berekenen van de offset als (periode - 2) * 0.2 is het probleem dat bij Periode 3 van het onderste forest_reserve het label in de grafiek wegvalt.  Ik heb er nu 2.5 van gemaakt, wat als nadeel heeft dat periode wel verder onder de lijn staat, maar voorlopig heb ik er nog geen problemen bij gezien.  Dit finaal nog eens goed testen: blijft alles zichtbaar?

# - als enkele bosreservaten geselecteerd worden, dan blijven de tussenliggende streepjes en labels staan in de grafiek.  De oorzaak is dat ik de factorlevels van forest_reserves gebruik om de locaties numeriek te berekenen (waarde voor Y en tickvals), beter zou zijn om de geselecteerde waarden oplopend te nummeren.  Maar op basis van het internet lijkt hier niet direct een oplossing voor te zijn want de vragen worden niet beantwoord:
#    - https://stackoverflow.com/questions/74973243/accessing-the-selected-value-from-filter-select-or-shareddata-object-crosstalk-r
#    - https://stackoverflow.com/questions/78873193/accessing-a-column-from-a-crosstalkshareddata-object-that-has-been-filtered-by

# Omdat de website statisch gebouwd wordt en die selectie bij het raadplegen van de website door de gebruiker gebeurt, is het onwaarschijnlijk dat dit in de R-code aangepast kunnen worden, dus waarschijnlijk moet hiervoor javascript toegevoegd worden
# Een gerelateerd issue met js: https://github.com/rstudio/crosstalk/issues/118
# html en js raadplegen: F12 of rechtsklikken en voor inspecteren kiezen


# in de html van de site:
# - in selection tool komen geselecteerde items onder select multiple="multiple" en bij class="selectize-control multi" onder class="selectize-input items not-full has-options has-items", dit zijn telkens enkel de geselecteerde reservaten
# - in grafiek staan meestal alle gridlijnen:
#     - bij class="cartesianlayer", class="subplot xy", class="gridlayer", class="y"
#     - bij class="cartesianlayer", class="subplot xy", class="yaxislayer-above", class="ytick" (ticks met labels)
# - in 'script' staat volledige gegevensset en dit wordt niet aangepast bij selectie van items

# getest of ik de as.numeric(as.factor(forest_reserve)) in y en tickvals van yaxis simpelweg kon vervangen door 1:n met n het aantal gekozen bosreservaten, maar dit geeft het label van bosreservaten 1:n in combinatie met de juiste gegevens die per periode op 1 lijn staan.

# dus overblijvende opties zijn: keuzes opvragen met js en hernummeren, of andere optie zoeken voor grafiek, bv. bars die niet getoond worden

# ... en na lang zoeken merk ik dat die tussenliggende reservaten ook al bij de originele grafiek zonder 'jitter' verschijnen, en bij andere grafiektypen (bv. bars), dus dit probleem heeft niks met de aanpassingen te maken.


bscols(widths = c(6, 6),
       sd %>%
        plot_ly(x = ~mean_BiomassAboveGr_t_ha, y = ~(as.numeric(as.factor(forest_reserve)) + offset_period), type = 'scatter', split = ~period, mode = 'markers',
                error_x = ~list(array = uci_diff_BiomassAboveGr_t_ha)) %>%
        layout(legend = list(title = list(text = 'Period')),
               xaxis = list(title = "Above ground biomass (ton /ha)"),
               yaxis = list(
                 title = "Forest reserve",
                 zeroline = FALSE,
                 tickmode = "array",
                 tickvals = ~unique(as.numeric(sort(as.factor(forest_reserve)))),
                 ticktext = ~unique(sort(as.factor(forest_reserve)))#,
                 #range = c(~min(as.numeric(as.factor(forest_reserve))) - 1, ~max(as.numeric(as.factor(forest_reserve))) + 1)
               )
        ),
       sd %>%
        plot_ly(x = ~mean_BiomassBelowGr_t_ha , y = ~(as.numeric(as.factor(forest_reserve)) + offset_period), type = 'scatter', split = ~period, mode = 'markers',
                error_x = ~list(array = uci_diff_BiomassBelowGr_t_ha)) %>%
        layout(legend = list(title = list(text = 'Period')),
               xaxis = list(title = "Below ground biomass (ton /ha)"),
               yaxis = list(
                 title = "Forest reserve",
                 zeroline = FALSE,
                 tickmode = "array",
                 tickvals = ~unique(as.numeric(sort(as.factor(forest_reserve)))),
                 ticktext = ~unique(sort(as.factor(forest_reserve)))#,
                 #range = c(~min(as.numeric(as.factor(forest_reserve))) - 1, ~max(as.numeric(as.factor(forest_reserve))) + 1)
               )
        )
)

bscols(widths = c(6, 6),
       sd %>%
        plot_ly(x = ~mean_CarbonAboveGr_t_ha, y = ~forest_reserve, type = 'scatter', split = ~period, mode = 'markers',
                error_x = ~list(array = uci_diff_CarbonAboveGr_t_ha)) %>%
        layout(legend = list(title = list(text = 'Period')),
               xaxis = list(title = "Above ground carbon (ton /ha)"),
               yaxis = list(title = "Forest reserve")),
       sd %>%
        plot_ly(x = ~mean_CarbonBelowGr_t_ha, y = ~forest_reserve, type = 'scatter', split = ~period, mode = 'markers',
                error_x = ~list(array = uci_diff_CarbonBelowGr_t_ha)) %>%
        layout(legend = list(title = list(text = 'Period')),
               xaxis = list(title = "Below ground carbon (ton /ha)"),
               yaxis = list(title = "Forest reserve")))
```

## Dendrometerie

```{r}

stat_dendro <- stat_dendro[!is.na(stat_dendro$vol_deadw_m3_ha),]

stat_dendro_wide <- left_join(stat_dendro, plotinfo, by=c("plot_id","period")) %>%
  select(forest_reserve, period, vol_alive_m3_ha, vol_deadw_m3_ha, vol_dead_standing_m3_ha, vol_log_m3_ha) %>%
  pivot_longer(cols = c("vol_alive_m3_ha", "vol_deadw_m3_ha", "vol_dead_standing_m3_ha", "vol_log_m3_ha"),
           names_to = "label", values_to = "value") %>%
  group_by(forest_reserve, period, label) %>%
  summarise(mean= mean(value), uci_diff= qnorm(1-0.05/2)*sd(value)/sqrt(n()))  %>%
  pivot_wider(names_from = "label", values_from = c("mean", "uci_diff"))

stat_dendro_wide$forest_reserve <- fct_reorder(stat_dendro_wide$forest_reserve, stat_dendro_wide$mean_vol_alive_m3_ha)
```

```{r}

sd <- SharedData$new(stat_dendro_wide)

bscols(widths = c(4, 4),
       filter_select("forest_reserve", "Select forest reserve", sd, ~forest_reserve),
       filter_checkbox("period", "Select period", sd, ~period))

bscols(widths = c(6, 6),
       sd %>%
        plot_ly(x = ~mean_vol_alive_m3_ha, y = ~forest_reserve, type = 'scatter', split = ~period, mode = 'markers',
                error_x = ~list(array = uci_diff_vol_alive_m3_ha)) %>%
        layout(legend = list(title = list(text = 'Period')),
               xaxis = list(title = "Volume living trees (m³ /ha)"),
               yaxis = list(title = "Forest reserve")),
       sd %>%
        plot_ly(x = ~mean_vol_deadw_m3_ha, y = ~forest_reserve, type = 'scatter', split = ~period, mode = 'markers',
                error_x = ~list(array = uci_diff_vol_deadw_m3_ha)) %>%
        layout(legend = list(title = list(text = 'Period')),
               xaxis = list(title = "Volume dead wood (m³ /ha)"),
               yaxis = list(title = "Forest reserve")))

bscols(widths = c(6, 6),
       sd %>%
        plot_ly(x = ~mean_vol_dead_standing_m3_ha, y = ~forest_reserve, type = 'scatter', split = ~period, mode = 'markers',
                error_x = ~list(array = uci_diff_vol_dead_standing_m3_ha)) %>%
        layout(legend = list(title = list(text = 'Period')),
               xaxis = list(title = "Volume standing dead wood (m³ /ha)"),
               yaxis = list(title = "Forest reserve")),
       sd %>%
        plot_ly(x = ~mean_vol_log_m3_ha, y = ~forest_reserve, type = 'scatter', split = ~period, mode = 'markers',
                error_x = ~list(array = uci_diff_vol_log_m3_ha)) %>%
        layout(legend = list(title = list(text = 'Period')),
               xaxis = list(title = "Volume lying dead wood (m³ /ha)"),
               yaxis = list(title = "Forest reserve")))
```
:::
