message = c(
  "",
  "> Autogenerated content below",
  "> Do not edit manually."
)

# Clean report file and remove child files
flandersqmd::autoqmd_finalise(
  qmd_files = "grafieken_per_reservaat.qmd",
  message = message,
  child_dirs_rm = "fiches_reservaat_qmd"
)

flandersqmd::post_render()
