on:
  push:
    branches-ignore:
      - gh-pages

name: check-project

jobs:
  check-src:
    runs-on: ubuntu-latest
    name: "check project with checklist"
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RSPM: "https://packagemanager.posit.co/cran/__linux__/noble/latest"
    permissions:
      contents: read
    steps:
      - name: "Check project with checklist"
        uses: inbo/actions/check_project@main
        with:
          cmd: |
            Rscript -e 'install.packages("pak")'
            Rscript -e 'pak::pkg_install("inbo/flandersqmd#7")'
